---
abstract: 'Unicode grapheme-level versions of built-in Perl functions'
author:
  - 'Nick Patch <patch@cpan.org>'
build_requires:
  Test::More: 0.41
  Test::Warn: 0.01
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Util
provides:
  Unicode::Util:
    file: lib/Unicode/Util.pm
    version: 0.07
requires:
  parent: 0
  perl: v5.8.0
resources:
  bugtracker: https://github.com/patch/unicode-util-pm5/issues
  homepage: https://github.com/patch/unicode-util-pm5
  license: http://dev.perl.org/licenses/
  repository: git://github.com/patch/unicode-util-pm5.git
version: 0.07
